# Site settings
gems: [jekyll-paginate]

# Dependencies
markdown:         kramdown
highlighter:      rouge
redcarpet:
  extensions: ["strikethrough"]

kramdown:
  input: GFM

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Reactive Spaces and Media Architecture
tagline:          'CMU - Fall 2018'
description:      'A hands-on introductory course exploring the Internet of Things and connected product experiences.'
--url:              "http://jmarsico.github.io/"
--baseurl:          "http://jmarsico.github.io/"
baseurl:          "/rsma2018"

author:
  name:           'Jakob Marsico'
  url:            http://jmarsico.github.io/rsma2018/

email: 			  jmarsico@gmail.com
twitter_username: n/a
github_username:  jmarsico
slack:				http://rsma2018.slack.com
gallery:			http://ideate.xsead.cmu.edu
facilities:			https://resources.ideate.cmu.edu/

paginate:         5

# Custom vars
version:          1.0.5

github:
  repo:           https://github.com/jmarsico/rsma2018
